# Generated by Django 4.1.1 on 2022-10-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inglizcha', models.CharField(max_length=120, verbose_name='Inglizcha')),
                ('uzbekcha', models.CharField(max_length=120, verbose_name="o'zbekcha")),
            ],
        ),
    ]
